//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.06 at 05:30:15 PM EET 
//


package ua.inf.iwanoff.attestation.model;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated inf the ua.inf.iwanoff.attestation.model package.
 * <p>An ObjectFactory allows you to programmatically
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided inf this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ua.inf.iwanoff.attestation.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WrsData }
     * 
     */
    public WrsData createWrsData() {
        return new WrsData();
    }

    /**
     * Create an instance of {@link WrsData.Sample }
     * 
     */
    public WrsData.Sample createWrsDataSample() {
        return new WrsData.Sample();
    }

    /**
     * Create an instance of {@link WrsData.Sample.X }
     * 
     */
    public WrsData.Sample.X createWrsDataSampleX() {
        return new WrsData.Sample.X();
    }

}
