//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.27 at 01:10:23 PM EEST 
//


package ua.inf.iwanoff.attestation.controller;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ua.inf.iwanoff.attestation.controller package. 
 * <p>An ObjectFactory allows you to programmatically
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ua.inf.iwanoff.attestation.controller
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Options }
     * 
     */
    public Options createOptions() {
        return new Options();
    }

    /**
     * Create an instance of {@link Options.Window }
     * 
     */
    public Options.Window createOptionsWindow() {
        return new Options.Window();
    }

    /**
     * Create an instance of {@link Options.ReportOptions }
     * 
     */
    public Options.ReportOptions createOptionsReportOptions() {
        return new Options.ReportOptions();
    }

}
