//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.27 at 01:10:23 PM EEST 
//


package ua.inf.iwanoff.attestation.controller;

import jakarta.xml.bind.JAXBContext;
import jakarta.xml.bind.JAXBException;
import jakarta.xml.bind.Marshaller;
import jakarta.xml.bind.Unmarshaller;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Window" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="Left" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="Top" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="Width" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="Height" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ReportOptions">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="CalcDisp" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="CalcHomo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="CalcDrift" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="StudentSides" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="CurrentDir" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Language" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "window",
    "reportOptions"
})
@XmlRootElement(name = "Options")
public class Options {

    @XmlElement(name = "Window")
    private Options.Window window = new Options.Window();
    @XmlElement(name = "ReportOptions", required = true)
    private Options.ReportOptions reportOptions = new Options.ReportOptions();
    @XmlAttribute(name = "CurrentDir")
    private String currentDir = ".";
    @XmlAttribute(name = "Language", required = true)
    private String language = "ENGLISH";

    /**
     * Gets the value of the window property.
     * 
     * @return
     *     possible object is
     *     {@link Options.Window }
     *     
     */
    public Options.Window getWindow() {
        return window;
    }

    /**
     * Sets the value of the window property.
     * 
     * @param value
     *     allowed object is
     *     {@link Options.Window }
     *     
     */
    public void setWindow(Options.Window value) {
        this.window = value;
    }

    /**
     * Gets the value of the reportOptions property.
     * 
     * @return
     *     possible object is
     *     {@link Options.ReportOptions }
     *     
     */
    public Options.ReportOptions getReportOptions() {
        return reportOptions;
    }

    /**
     * Sets the value of the reportOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Options.ReportOptions }
     *     
     */
    public void setReportOptions(Options.ReportOptions value) {
        this.reportOptions = value;
    }

    /**
     * Gets the value of the currentDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentDir() {
        return currentDir;
    }

    /**
     * Sets the value of the currentDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentDir(String value) {
        this.currentDir = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="CalcDisp" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="CalcHomo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="CalcDrift" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="StudentSides" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ReportOptions {

        @XmlAttribute(name = "CalcDisp", required = true)
        private String calcDisp;
        @XmlAttribute(name = "CalcHomo", required = true)
        private String calcHomo;
        @XmlAttribute(name = "CalcDrift", required = true)
        private String calcDrift;
        @XmlAttribute(name = "StudentSides", required = true)
        private int studentSides = 1;

        /**
         * Gets the value of the calcDisp property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCalcDisp() {
            return calcDisp != null ? calcDisp : "true";
        }

        /**
         * Sets the value of the calcDisp property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCalcDisp(String value) {
            this.calcDisp = value;
        }

        /**
         * Gets the value of the calcHomo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCalcHomo() {
            return calcHomo != null ? calcHomo : "true";
        }

        /**
         * Sets the value of the calcHomo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCalcHomo(String value) {
            this.calcHomo = value;
        }

        /**
         * Gets the value of the calcDrift property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCalcDrift() {
            return calcDrift != null ? calcDrift : "true";
        }

        /**
         * Sets the value of the calcDrift property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCalcDrift(String value) {
            this.calcDrift = value;
        }

        /**
         * Gets the value of the studentSides property.
         * 
         */
        public int getStudentSides() {
            return studentSides;
        }

        /**
         * Sets the value of the studentSides property.
         * 
         */
        public void setStudentSides(int value) {
            this.studentSides = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="Left" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="Top" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="Width" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="Height" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Window {

        @XmlAttribute(name = "Left", required = true)
        private int left = 100;
        @XmlAttribute(name = "Top", required = true)
        private int top = 200;
        @XmlAttribute(name = "Width", required = true)
        private int width = 1295;
        @XmlAttribute(name = "Height", required = true)
        private int height = 700;

        /**
         * Gets the value of the left property.
         * 
         */
        public Integer getLeft() {
            return left;
        }

        /**
         * Sets the value of the left property.
         * 
         */
        public void setLeft(int value) {
            this.left = value;
        }

        /**
         * Gets the value of the top property.
         * 
         */
        public Integer getTop() {
            return top;
        }

        /**
         * Sets the value of the top property.
         * 
         */
        public void setTop(int value) {
            this.top = value;
        }

        /**
         * Gets the value of the width property.
         * 
         */
        public Integer getWidth() {
            return width;
        }

        /**
         * Sets the value of the width property.
         * 
         */
        public void setWidth(int value) {
            this.width = value;
        }

        /**
         * Gets the value of the height property.
         * 
         */
        public Integer getHeight() {
            return height;
        }

        /**
         * Sets the value of the height property.
         * 
         */
        public void setHeight(int value) {
            this.height = value;
        }

    }

    public static Options readOptions(String fileName) throws FileNotFoundException {
        try {
            JAXBContext jaxbContext = JAXBContext.newInstance("ua.inf.iwanoff.attestation.controller");
            Unmarshaller unmarshaller = jaxbContext.createUnmarshaller();
            return (Options) unmarshaller.unmarshal(new FileInputStream(fileName));
        }
        catch (JAXBException e) {
            return new Options();
        }
    }

    public boolean saveOptions(String fileName) {
        try {
            JAXBContext jaxbContext = JAXBContext.newInstance("ua.inf.iwanoff.attestation.controller");
            Marshaller marshaller = jaxbContext.createMarshaller();
            marshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, Boolean.TRUE);
            marshaller.marshal(this, new FileOutputStream(fileName));
            return true;
        }
        catch (JAXBException | FileNotFoundException e) {
            e.printStackTrace();
            return false;
        }
    }

}
